"""create backend core tables

Revision ID: 7391d7cbd0c4
Revises: 
Create Date: 2026-05-11 19:05:56.427815

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7391d7cbd0c4'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_deliveries_courier_status', table_name='deliveries')
    op.drop_table('deliveries')
    op.drop_table('payments')
    op.drop_table('restaurant_categories')
    op.drop_table('reviews')
    op.drop_table('user_addresses')
    op.add_column('couriers', sa.Column('phone_number', sa.String(length=30), nullable=False))
    op.add_column('couriers', sa.Column('is_available', sa.Boolean(), nullable=False))
    op.add_column('couriers', sa.Column('current_order_id', sa.Integer(), nullable=True))
    op.alter_column('couriers', 'full_name',
               existing_type=sa.VARCHAR(length=150),
               type_=sa.String(length=100),
               existing_nullable=False)
    op.drop_constraint('couriers_phone_key', 'couriers', type_='unique')
    op.create_index(op.f('ix_couriers_id'), 'couriers', ['id'], unique=False)
    op.create_unique_constraint(None, 'couriers', ['phone_number'])
    op.drop_column('couriers', 'phone')
    op.drop_column('couriers', 'created_at')
    op.drop_column('couriers', 'status')
    op.drop_index('idx_menu_items_restaurant_available', table_name='menu_items')
    op.drop_constraint('uq_menu_item_per_restaurant', 'menu_items', type_='unique')
    op.create_index(op.f('ix_menu_items_id'), 'menu_items', ['id'], unique=False)
    op.create_index(op.f('ix_menu_items_restaurant_id'), 'menu_items', ['restaurant_id'], unique=False)
    op.drop_constraint('menu_items_restaurant_id_fkey', 'menu_items', type_='foreignkey')
    op.create_foreign_key(None, 'menu_items', 'restaurants', ['restaurant_id'], ['id'])
    op.drop_column('menu_items', 'created_at')
    op.add_column('order_items', sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False))
    op.drop_constraint('uq_order_menu_item', 'order_items', type_='unique')
    op.create_index(op.f('ix_order_items_id'), 'order_items', ['id'], unique=False)
    op.create_index(op.f('ix_order_items_menu_item_id'), 'order_items', ['menu_item_id'], unique=False)
    op.create_index(op.f('ix_order_items_order_id'), 'order_items', ['order_id'], unique=False)
    op.drop_constraint('order_items_order_id_fkey', 'order_items', type_='foreignkey')
    op.drop_constraint('order_items_menu_item_id_fkey', 'order_items', type_='foreignkey')
    op.create_foreign_key(None, 'order_items', 'menu_items', ['menu_item_id'], ['id'])
    op.create_foreign_key(None, 'order_items', 'orders', ['order_id'], ['id'])
    op.drop_column('order_items', 'unit_price')
    op.alter_column('order_status_history', 'old_status',
               existing_type=sa.VARCHAR(length=30),
               type_=sa.String(length=50),
               existing_nullable=True)
    op.alter_column('order_status_history', 'new_status',
               existing_type=sa.VARCHAR(length=30),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.alter_column('order_status_history', 'changed_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index('idx_order_status_history_order_time', table_name='order_status_history')
    op.create_index(op.f('ix_order_status_history_id'), 'order_status_history', ['id'], unique=False)
    op.create_index(op.f('ix_order_status_history_order_id'), 'order_status_history', ['order_id'], unique=False)
    op.drop_constraint('order_status_history_order_id_fkey', 'order_status_history', type_='foreignkey')
    op.create_foreign_key(None, 'order_status_history', 'orders', ['order_id'], ['id'])
    op.add_column('orders', sa.Column('customer_id', sa.Integer(), nullable=False))
    op.add_column('orders', sa.Column('courier_id', sa.Integer(), nullable=True))
    op.add_column('orders', sa.Column('delivery_address', sa.Text(), nullable=False))
    op.add_column('orders', sa.Column('total_price', sa.Numeric(precision=10, scale=2), nullable=False))
    op.alter_column('orders', 'status',
               existing_type=sa.VARCHAR(length=30),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.alter_column('orders', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index('idx_orders_restaurant_status', table_name='orders')
    op.drop_index('idx_orders_user_created_at', table_name='orders')
    op.create_index(op.f('ix_orders_courier_id'), 'orders', ['courier_id'], unique=False)
    op.create_index(op.f('ix_orders_customer_id'), 'orders', ['customer_id'], unique=False)
    op.create_index(op.f('ix_orders_id'), 'orders', ['id'], unique=False)
    op.create_index(op.f('ix_orders_restaurant_id'), 'orders', ['restaurant_id'], unique=False)
    op.drop_constraint('orders_restaurant_id_fkey', 'orders', type_='foreignkey')
    op.drop_constraint('orders_address_id_fkey', 'orders', type_='foreignkey')
    op.drop_constraint('orders_user_id_fkey', 'orders', type_='foreignkey')
    op.create_foreign_key(None, 'orders', 'users', ['customer_id'], ['id'])
    op.create_foreign_key(None, 'orders', 'restaurants', ['restaurant_id'], ['id'])
    op.create_foreign_key(None, 'orders', 'couriers', ['courier_id'], ['id'])
    op.drop_column('orders', 'updated_at')
    op.drop_column('orders', 'address_id')
    op.drop_column('orders', 'total_amount')
    op.drop_column('orders', 'user_id')
    op.add_column('restaurants', sa.Column('category', sa.String(length=100), nullable=True))
    op.add_column('restaurants', sa.Column('is_open', sa.Boolean(), nullable=False))
    op.alter_column('restaurants', 'address',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.drop_index('idx_restaurants_category_active', table_name='restaurants')
    op.drop_index('idx_restaurants_name_trgm', table_name='restaurants', postgresql_using='gin')
    op.create_index(op.f('ix_restaurants_id'), 'restaurants', ['id'], unique=False)
    op.create_index(op.f('ix_restaurants_name'), 'restaurants', ['name'], unique=False)
    op.drop_constraint('restaurants_category_id_fkey', 'restaurants', type_='foreignkey')
    op.drop_constraint('restaurants_owner_id_fkey', 'restaurants', type_='foreignkey')
    op.drop_column('restaurants', 'owner_id')
    op.drop_column('restaurants', 'created_at')
    op.drop_column('restaurants', 'category_id')
    op.drop_column('restaurants', 'rating')
    op.drop_column('restaurants', 'phone')
    op.drop_column('restaurants', 'is_active')
    op.add_column('users', sa.Column('hashed_password', sa.String(length=255), nullable=False))
    op.alter_column('users', 'full_name',
               existing_type=sa.VARCHAR(length=150),
               type_=sa.String(length=100),
               existing_nullable=False)
    op.alter_column('users', 'role',
               existing_type=sa.VARCHAR(length=30),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.drop_constraint('users_email_key', 'users', type_='unique')
    op.drop_constraint('users_phone_key', 'users', type_='unique')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.drop_column('users', 'password_hash')
    op.drop_column('users', 'created_at')
    op.drop_column('users', 'phone')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('phone', sa.VARCHAR(length=30), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('password_hash', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_unique_constraint('users_phone_key', 'users', ['phone'])
    op.create_unique_constraint('users_email_key', 'users', ['email'])
    op.alter_column('users', 'role',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=30),
               existing_nullable=False)
    op.alter_column('users', 'full_name',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=150),
               existing_nullable=False)
    op.drop_column('users', 'hashed_password')
    op.add_column('restaurants', sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('restaurants', sa.Column('phone', sa.VARCHAR(length=30), autoincrement=False, nullable=True))
    op.add_column('restaurants', sa.Column('rating', sa.NUMERIC(precision=2, scale=1), autoincrement=False, nullable=False))
    op.add_column('restaurants', sa.Column('category_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('restaurants', sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.add_column('restaurants', sa.Column('owner_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('restaurants_owner_id_fkey', 'restaurants', 'users', ['owner_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('restaurants_category_id_fkey', 'restaurants', 'restaurant_categories', ['category_id'], ['id'], ondelete='SET NULL')
    op.drop_index(op.f('ix_restaurants_name'), table_name='restaurants')
    op.drop_index(op.f('ix_restaurants_id'), table_name='restaurants')
    op.create_index('idx_restaurants_name_trgm', 'restaurants', ['name'], unique=False, postgresql_using='gin')
    op.create_index('idx_restaurants_category_active', 'restaurants', ['category_id', 'is_active'], unique=False)
    op.alter_column('restaurants', 'address',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_column('restaurants', 'is_open')
    op.drop_column('restaurants', 'category')
    op.add_column('orders', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('orders', sa.Column('total_amount', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False))
    op.add_column('orders', sa.Column('address_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('orders', sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.create_foreign_key('orders_user_id_fkey', 'orders', 'users', ['user_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key('orders_address_id_fkey', 'orders', 'user_addresses', ['address_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('orders_restaurant_id_fkey', 'orders', 'restaurants', ['restaurant_id'], ['id'], ondelete='RESTRICT')
    op.drop_index(op.f('ix_orders_restaurant_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_customer_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_courier_id'), table_name='orders')
    op.create_index('idx_orders_user_created_at', 'orders', ['user_id', 'created_at'], unique=False)
    op.create_index('idx_orders_restaurant_status', 'orders', ['restaurant_id', 'status'], unique=False)
    op.alter_column('orders', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('orders', 'status',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=30),
               existing_nullable=False)
    op.drop_column('orders', 'total_price')
    op.drop_column('orders', 'delivery_address')
    op.drop_column('orders', 'courier_id')
    op.drop_column('orders', 'customer_id')
    op.drop_constraint(None, 'order_status_history', type_='foreignkey')
    op.create_foreign_key('order_status_history_order_id_fkey', 'order_status_history', 'orders', ['order_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_order_status_history_order_id'), table_name='order_status_history')
    op.drop_index(op.f('ix_order_status_history_id'), table_name='order_status_history')
    op.create_index('idx_order_status_history_order_time', 'order_status_history', ['order_id', 'changed_at'], unique=False)
    op.alter_column('order_status_history', 'changed_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('order_status_history', 'new_status',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=30),
               existing_nullable=False)
    op.alter_column('order_status_history', 'old_status',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=30),
               existing_nullable=True)
    op.add_column('order_items', sa.Column('unit_price', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'order_items', type_='foreignkey')
    op.drop_constraint(None, 'order_items', type_='foreignkey')
    op.create_foreign_key('order_items_menu_item_id_fkey', 'order_items', 'menu_items', ['menu_item_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key('order_items_order_id_fkey', 'order_items', 'orders', ['order_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_order_items_order_id'), table_name='order_items')
    op.drop_index(op.f('ix_order_items_menu_item_id'), table_name='order_items')
    op.drop_index(op.f('ix_order_items_id'), table_name='order_items')
    op.create_unique_constraint('uq_order_menu_item', 'order_items', ['order_id', 'menu_item_id'])
    op.drop_column('order_items', 'price')
    op.add_column('menu_items', sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'menu_items', type_='foreignkey')
    op.create_foreign_key('menu_items_restaurant_id_fkey', 'menu_items', 'restaurants', ['restaurant_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_menu_items_restaurant_id'), table_name='menu_items')
    op.drop_index(op.f('ix_menu_items_id'), table_name='menu_items')
    op.create_unique_constraint('uq_menu_item_per_restaurant', 'menu_items', ['restaurant_id', 'name'])
    op.create_index('idx_menu_items_restaurant_available', 'menu_items', ['restaurant_id', 'is_available'], unique=False)
    op.add_column('couriers', sa.Column('status', sa.VARCHAR(length=30), autoincrement=False, nullable=False))
    op.add_column('couriers', sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.add_column('couriers', sa.Column('phone', sa.VARCHAR(length=30), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'couriers', type_='unique')
    op.drop_index(op.f('ix_couriers_id'), table_name='couriers')
    op.create_unique_constraint('couriers_phone_key', 'couriers', ['phone'])
    op.alter_column('couriers', 'full_name',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=150),
               existing_nullable=False)
    op.drop_column('couriers', 'current_order_id')
    op.drop_column('couriers', 'is_available')
    op.drop_column('couriers', 'phone_number')
    op.create_table('user_addresses',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('user_addresses_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('address_line', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('city', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('latitude', sa.NUMERIC(precision=9, scale=6), autoincrement=False, nullable=True),
    sa.Column('longitude', sa.NUMERIC(precision=9, scale=6), autoincrement=False, nullable=True),
    sa.Column('is_default', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='user_addresses_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='user_addresses_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('reviews',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('restaurant_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('order_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('rating', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('comment', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.CheckConstraint('rating >= 1 AND rating <= 5', name='chk_review_rating'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name='reviews_order_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurants.id'], name='reviews_restaurant_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='reviews_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='reviews_pkey'),
    sa.UniqueConstraint('order_id', name='reviews_order_id_key')
    )
    op.create_table('restaurant_categories',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('restaurant_categories_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='restaurant_categories_pkey'),
    sa.UniqueConstraint('name', name='restaurant_categories_name_key'),
    postgresql_ignore_search_path=False
    )
    op.create_table('payments',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('order_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('method', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.Column('amount', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.CheckConstraint("method::text = ANY (ARRAY['cash'::character varying, 'card'::character varying, 'wallet'::character varying]::text[])", name='chk_payment_method'),
    sa.CheckConstraint("status::text = ANY (ARRAY['pending'::character varying, 'paid'::character varying, 'failed'::character varying, 'refunded'::character varying]::text[])", name='chk_payment_status'),
    sa.CheckConstraint('amount >= 0::numeric', name='chk_payment_amount'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name='payments_order_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='payments_pkey'),
    sa.UniqueConstraint('order_id', name='payments_order_id_key')
    )
    op.create_table('deliveries',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('order_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('courier_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.Column('picked_up_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('delivered_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.CheckConstraint("status::text = ANY (ARRAY['assigned'::character varying, 'picked_up'::character varying, 'delivered'::character varying, 'failed'::character varying]::text[])", name='chk_delivery_status'),
    sa.ForeignKeyConstraint(['courier_id'], ['couriers.id'], name='deliveries_courier_id_fkey', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name='deliveries_order_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='deliveries_pkey'),
    sa.UniqueConstraint('order_id', name='deliveries_order_id_key')
    )
    op.create_index('idx_deliveries_courier_status', 'deliveries', ['courier_id', 'status'], unique=False)
    # ### end Alembic commands ###
